name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

jobs:
  with-babel-plugin:
    name: Chromatic (with babel plugin)
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: 19f9e41ca7b7
          workingDir: examples/with-babel-plugin
          exitOnceUploaded: true
          ignoreLastBuildOnBranch: true

  without-babel-plugin:
    name: Chromatic (without babel plugin)
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: fbff17ee1545
          workingDir: examples/without-babel-plugin
          exitOnceUploaded: true
          ignoreLastBuildOnBranch: true
