name: "Chromatic (with-babel-plugin)"

on: push

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn
      - name: Build dependencies
        run: yarn build
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN_WITH_BABEL_PLUGIN }}
          workingDir: examples/with-babel-plugin
          autoAcceptChanges: main
          exitOnceUploaded: true
